In [30]:
import numpy as np
a = np.random.randint(10, 100, 60).reshape(3,5,4)

In [31]:
a

array([[[14, 38, 18, 80],
        [50, 19, 15, 99],
        [93, 41, 56, 76],
        [39, 22, 98, 69],
        [36, 17, 59, 68]],

       [[12, 26, 29, 77],
        [55, 51, 71, 91],
        [62, 72, 69, 51],
        [16, 45, 75, 73],
        [80, 54, 88, 40]],

       [[52, 16, 34, 88],
        [91, 41, 14, 49],
        [20, 61, 79, 29],
        [39, 51, 92, 48],
        [61, 11, 35, 57]]])

In [32]:
a.argmin(axis=0)

array([[1, 2, 0, 1],
       [0, 0, 2, 2],
       [2, 0, 0, 2],
       [1, 0, 1, 2],
       [0, 2, 2, 1]])

In [33]:
a.argmin(axis=1)

array([[0, 4, 1, 4],
       [0, 0, 0, 4],
       [2, 4, 1, 2]])

In [34]:
a.argmin(axis=2)

array([[0, 2, 1, 1, 1],
       [0, 1, 3, 0, 3],
       [1, 2, 0, 0, 1]])